### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by habibaghasafari** [rajetic/OculusMonitor#1]
Hi
Thank you very much for your wonderful code. It is absolutely awesome. But can you add tracking data (position and orientation) for the headset as well?

**Comment by habibaghasafari** [comment]
Hi
I just realized that you provide headset tracking data in the "Room Layout" section. I can take the tracking data from there.
But I think it's better to include it in the main headset window so people can see it the first time.

**Comment by rajetic** [comment]
That's a good point, I don't know why I didn't add that.
So I just did. Version 0.2.3 has headset position, orientation and velocity shown in the headset panel.

I also realised I've had it in eye level tracking this whole time, so I added a checkbox to choose floor level (ground is at 0m) and eye level tracking (ground is at -height).

**Comment by habibaghasafari** [comment]
thank you very much.
